"""empty message

Revision ID: 022ec36136c2
Revises: e553f35142f3
Create Date: 2021-06-03 21:21:44.931685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '022ec36136c2'
down_revision = 'e553f35142f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'created_date')
    # ### end Alembic commands ###
